twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig', 'components/_form_theme_comment_list.html.twig']

when@test:
    twig:
        strict_variables: true
